[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 10

[preview]
tab_size = 2
max_width = 1500
max_height = 1200
image_filter = "lanczos3"
image_quality = 90
ueberzug_scale = 1

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
